services:
  project-service:
    build:
      context: ..
      dockerfile: project/Dockerfile
    container_name: project-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "18085:18085"
    restart: unless-stopped