services:
  user-postgres:
    image: postgres:17-alpine
    container_name: user-postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_INITDB_ARGS: "-E UTF8"
      TZ: Asia/Seoul
    ports:
      - "5431:5432"
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    networks:
      - user-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d user_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ..
      dockerfile: user/Dockerfile
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: local
      USER_SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5431/user_db
      USER_SPRING_DATASOURCE_USERNAME: user
      USER_SPRING_DATASOURCE_PASSWORD: 1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
    ports:
      - "18081:18081"
    depends_on:
      user-postgres:
        condition: service_healthy
    networks:
      - user-network
    restart: unless-stopped

volumes:
  user-postgres-data:
    driver: local

networks:
  user-network:
    driver: bridge
  msa-network:
    external: true